# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ZettelGeist
# email: your-email@example.com
description: >-
  A terminal-based note-taking system.
repository: "ZettelGeist/zettelgeist.github.io"
source: .
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zettelgeist.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
github_username: ZettelGeist

# Build settings
# theme: minima
remote_theme: jekyll/minima
# plugins:
#   - jekyll-feed

minima:
  skin: dark

# Conversion
markdown: kramdown
highlighter: rouge
incremental: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Github requirements
lsi: false
safe: true # this setting causes bundle to throw the error reported here in local builds https://github.com/pages-themes/leap-day/issues/4
gist:
  noscript: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
